#!/usr/bin/env python3
"""Emit a tiny Morello purecap object-JIT assembly stub for one uBPF shape.

Supported eBPF shapes for now:
    r0 = *(u64 *)(r1 + offset)
    exit

    rN = r1
    r0 = *(u64 *)(rN + offset)
    exit

Purecap ABI mapping for this proof:
    r1/context is passed in c0
    return scalar is x0
"""

import argparse
from pathlib import Path
from typing import Optional

EBPF_OP_LDXDW = 0x79
EBPF_OP_MOV64_REG = 0xBF
EBPF_OP_EXIT = 0x95


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--program-hex", help="raw eBPF bytecode as hex bytes")
    source.add_argument("--program-file", help="file containing raw eBPF bytecode")
    source.add_argument("--offset", type=int, help="debug mode: emit a context load for this byte offset")
    parser.add_argument("--output", required=True, help="assembly file to write")
    parser.add_argument("--symbol", default="bpf_entry", help="exported function symbol")
    return parser.parse_args()


def validate_symbol(symbol: str) -> None:
    if not symbol.replace("_", "a").isalnum() or symbol[0].isdigit():
        raise SystemExit(f"unsupported symbol name: {symbol!r}")


def parse_program_hex(program_hex: str) -> bytes:
    normalized = program_hex.replace(",", " ").replace("\\x", " ").replace("0x", " ")
    tokens = normalized.split()
    if len(tokens) == 1 and len(tokens[0]) > 2:
        compact = tokens[0]
        if len(compact) % 2 != 0:
            raise SystemExit("compact hex bytecode must have an even number of digits")
        tokens = [compact[i : i + 2] for i in range(0, len(compact), 2)]

    try:
        return bytes(int(token, 16) for token in tokens)
    except ValueError as exc:
        raise SystemExit(f"invalid hex byte in --program-hex: {exc}") from exc


def read_program(args: argparse.Namespace) -> Optional[bytes]:
    if args.program_hex is not None:
        return parse_program_hex(args.program_hex)
    if args.program_file is not None:
        return Path(args.program_file).read_bytes()
    return None


def parse_i16_le(data: bytes) -> int:
    return int.from_bytes(data, byteorder="little", signed=True)


def parse_i32_le(data: bytes) -> int:
    return int.from_bytes(data, byteorder="little", signed=True)


def decode_regs(insn: bytes) -> tuple[int, int]:
    regs = insn[1]
    return regs & 0x0F, regs >> 4


def offset_from_supported_program(program: bytes) -> int:
    if len(program) == 16:
        context_reg = 1
        load = program[:8]
        exit_insn = program[8:]
    elif len(program) == 24:
        alias = program[:8]
        alias_dst, alias_src = decode_regs(alias)
        alias_offset = parse_i16_le(alias[2:4])
        alias_imm = parse_i32_le(alias[4:8])
        if (
            alias[0] != EBPF_OP_MOV64_REG
            or alias_src != 1
            or alias_dst < 2
            or alias_dst > 9
            or alias_offset != 0
            or alias_imm != 0
        ):
            raise SystemExit("unsupported eBPF shape; expected leading 'rN = r1' alias")
        context_reg = alias_dst
        load = program[8:16]
        exit_insn = program[16:]
    else:
        raise SystemExit(f"unsupported eBPF program length {len(program)}; expected 16 or 24 bytes")

    opcode = load[0]
    dst, src = decode_regs(load)
    offset = parse_i16_le(load[2:4])
    imm = parse_i32_le(load[4:8])

    if opcode != EBPF_OP_LDXDW or dst != 0 or src != context_reg or imm != 0:
        raise SystemExit(
            "unsupported eBPF shape; expected 'r0 = *(u64 *)(context + offset)' "
            f"but got opcode=0x{opcode:02x} dst={dst} src={src} imm={imm}"
        )

    if exit_insn != bytes([EBPF_OP_EXIT, 0, 0, 0, 0, 0, 0, 0]):
        raise SystemExit("unsupported eBPF shape; final instruction must be plain EXIT")

    return offset


def validate_offset(offset: int) -> None:
    if offset < 0:
        raise SystemExit("negative context-load offsets are not implemented yet")
    if offset % 8 != 0:
        raise SystemExit("u64 context-load offsets must be 8-byte aligned")
    if offset // 8 >= 0x1000:
        raise SystemExit("offset too large for Morello/AArch64 unsigned scaled ldr immediate")


def emit_assembly(symbol: str, offset: int, source_comment: str) -> str:
    return f"""/* Generated by tools/cheri_objjit_emit.py.\n * Source: {source_comment}\n */
.text
.p2align 4
.globl {symbol}
.type {symbol},@function
{symbol}:
	ldr x0, [c0, #{offset}]
	ret c30
.size {symbol}, .-{symbol}
"""


def main() -> int:
    args = parse_args()
    validate_symbol(args.symbol)

    program = read_program(args)
    if program is None:
        offset = args.offset
        source_comment = f"debug offset={offset}"
    else:
        offset = offset_from_supported_program(program)
        source_comment = "eBPF bytes " + program.hex(" ")

    validate_offset(offset)
    Path(args.output).write_text(emit_assembly(args.symbol, offset, source_comment))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
